import 'package:flutter/material.dart';

final Map<String, List<IconData>> iconsByCategory = {
  'all': [
    Icons.favorite,
    Icons.star,
    Icons.thumb_up,
    Icons.trending_up,
    Icons.home,
    Icons.access_time,
    Icons.fitness_center,
    Icons.directions_run,
    Icons.sports_basketball,
    Icons.sports_football,
    Icons.sports_soccer,
    Icons.sports_tennis,
    Icons.pool,
    Icons.directions_bike,
    Icons.sports_gymnastics,
    Icons.restaurant,
    Icons.no_food,
    Icons.fastfood,
    Icons.local_drink,
    Icons.ramen_dining,
    Icons.set_meal,
    Icons.local_dining,
    Icons.lunch_dining,
    Icons.pets,
    Icons.bug_report,
    Icons.bug_report_outlined,
    Icons.bug_report_rounded,
    Icons.bug_report_sharp,
    Icons.mood_bad,
    Icons.warning,
    Icons.sentiment_dissatisfied,
    Icons.error,
    Icons.cancel,
    Icons.do_not_disturb,
    Icons.remove_circle,
    Icons.palette,
    Icons.music_note,
    Icons.book,
    Icons.brush,
    Icons.movie,
    Icons.sports_esports,
    Icons.photo_camera,
    Icons.mic,
    Icons.access_time,
    Icons.alarm,
    Icons.schedule,
    Icons.task,
    Icons.done,
    Icons.track_changes,
    Icons.timeline,
    Icons.calendar_month,
    Icons.people,
    Icons.person,
    Icons.person_add,
    Icons.group,
    Icons.favorite,
    Icons.handshake,
    Icons.family_restroom,
    Icons.flag,
    Icons.outlined_flag,
    Icons.assistant_photo,
    Icons.emoji_flags,
    Icons.flag_circle,
  ],

  'popular': [
    Icons.favorite,
    Icons.star,
    Icons.thumb_up,
    Icons.trending_up,
    Icons.home,
    Icons.access_time,
  ],

  'sports': [
    Icons.fitness_center,
    Icons.directions_run,
    Icons.sports_basketball,
    Icons.sports_football,
    Icons.sports_soccer,
    Icons.sports_tennis,
    Icons.pool,
    Icons.directions_bike,
    Icons.sports_gymnastics,
  ],

  'diet': [
    Icons.restaurant,
    Icons.no_food,
    Icons.fastfood,
    Icons.local_drink,
    Icons.ramen_dining,
    Icons.set_meal,
    Icons.local_dining,
    Icons.lunch_dining,
  ],

  'animals': [
    Icons.pets,
    Icons.bug_report,
    Icons.bug_report_outlined,
    Icons.bug_report_rounded,
    Icons.bug_report_sharp,
  ],

  'negative': [
    Icons.mood_bad,
    Icons.warning,
    Icons.sentiment_dissatisfied,
    Icons.error,
    Icons.cancel,
    Icons.do_not_disturb,
    Icons.remove_circle,
  ],

  'hobby': [
    Icons.palette,
    Icons.music_note,
    Icons.book,
    Icons.brush,
    Icons.movie,
    Icons.sports_esports,
    Icons.photo_camera,
    Icons.mic,
  ],

  'efficiency': [
    Icons.access_time,
    Icons.alarm,
    Icons.schedule,
    Icons.task,
    Icons.done,
    Icons.track_changes,
    Icons.timeline,
    Icons.calendar_month,
  ],

  'relationships': [
    Icons.people,
    Icons.person,
    Icons.person_add,
    Icons.group,
    Icons.favorite,
    Icons.handshake,
    Icons.family_restroom,
  ],

  'flags': [
    Icons.flag,
    Icons.outlined_flag,
    Icons.assistant_photo,
    Icons.emoji_flags,
    Icons.flag_circle,
  ],
};
